# Generated by Django 6.0.7 on 2026-07-20 16:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('adjustment', 'Ajuste'), ('return', 'Devolución')], max_length=20, verbose_name='tipo de movimiento')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad')),
                ('previous_stock', models.PositiveIntegerField(verbose_name='stock anterior')),
                ('new_stock', models.PositiveIntegerField(verbose_name='stock resultante')),
                ('reason', models.CharField(max_length=255, verbose_name='motivo')),
                ('reference', models.CharField(blank=True, help_text='Ejemplo: compra, pedido, factura o devolución.', max_length=100, verbose_name='referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='inventory_i_product_c37810_idx'), models.Index(fields=['movement_type'], name='inventory_i_movemen_e5f549_idx'), models.Index(fields=['created_by'], name='inventory_i_created_24d92c_idx')],
            },
        ),
    ]
