import axios from "axios";
import { MailCheck } from "lucide-react";
import { type FormEvent, useState } from "react";
import { Link } from "react-router";
import { requestPasswordReset } from "../../api/auth";

export function ForgotPasswordPage() {
  const [sent, setSent] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); try { const form = new FormData(event.currentTarget); await requestPasswordReset(String(form.get("email"))); setSent(true); } catch (cause) { setError(axios.isAxiosError(cause) ? "No pudimos procesar la solicitud." : "Ocurrió un error inesperado."); } finally { setLoading(false); } }
  return <main className="site-container py-16 sm:py-24"><section className="mx-auto max-w-lg rounded-[24px] border border-[#e1e7ef] bg-white p-8 shadow-[0_25px_70px_rgba(13,38,76,0.1)] sm:p-11"><div className="flex size-13 items-center justify-center rounded-2xl bg-[#eaf7fc] text-[#249fd3]"><MailCheck size={24} /></div>{sent ? <><p className="eyebrow mt-7">Revisa tu correo</p><h1 className="mt-3 text-3xl font-black tracking-tight">Solicitud enviada</h1><p className="mt-4 text-sm leading-7 text-[#66758a]">Si existe una cuenta asociada, recibirás un enlace para crear una contraseña nueva. En desarrollo, el enlace aparecerá en la consola de Django.</p><Link to="/login" className="mt-7 inline-flex w-full justify-center rounded-xl bg-[#249fd3] px-5 py-3.5 text-sm font-black text-white">Volver a iniciar sesión</Link></> : <><p className="eyebrow mt-7">Recuperar acceso</p><h1 className="mt-3 text-3xl font-black tracking-tight">¿Olvidaste tu contraseña?</h1><p className="mt-3 text-sm leading-6 text-[#6c798a]">Ingresa tu correo y te enviaremos un enlace seguro.</p><form onSubmit={submit} className="mt-7"><label className="text-sm font-bold">Correo electrónico<input name="email" type="email" required autoComplete="email" className="mt-2 w-full rounded-xl border border-[#dce4ef] bg-[#f8fafc] px-4 py-3.5 outline-none focus:border-[#249fd3] focus:ring-4 focus:ring-[#249fd3]/10" /></label>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<button disabled={loading} className="mt-5 w-full rounded-xl bg-[#249fd3] px-5 py-3.5 text-sm font-black text-white disabled:opacity-60">{loading ? "Enviando..." : "Enviar enlace"}</button></form><Link to="/login" className="mt-5 block text-center text-sm font-bold text-[#249fd3]">Volver a iniciar sesión</Link></>}</section></main>;
}
