import axios from "axios";
import { KeyRound } from "lucide-react";
import { type FormEvent, useState } from "react";
import { Link, useParams } from "react-router";
import { confirmPasswordReset } from "../../api/auth";

export function ResetPasswordPage() {
  const { uid = "", token = "" } = useParams(); const [done, setDone] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const password = String(form.get("password")); const confirm = String(form.get("password_confirm")); if (password !== confirm) { setError("Las contraseñas no coinciden."); return; } setLoading(true); try { await confirmPasswordReset(uid, token, password, confirm); setDone(true); } catch (cause) { setError(axios.isAxiosError(cause) && cause.response?.data?.detail ? String(cause.response.data.detail) : "La contraseña no cumple los requisitos de seguridad."); } finally { setLoading(false); } }
  return <main className="site-container py-16 sm:py-24"><section className="mx-auto max-w-lg rounded-[24px] border border-[#e1e7ef] bg-white p-8 shadow-[0_25px_70px_rgba(13,38,76,0.1)] sm:p-11"><div className="flex size-13 items-center justify-center rounded-2xl bg-[#edf3ff] text-[#1454d8]"><KeyRound size={24} /></div>{done ? <><h1 className="mt-7 text-3xl font-black tracking-tight">Contraseña actualizada</h1><p className="mt-4 text-sm leading-7 text-[#66758a]">Ya puedes ingresar a tu cuenta con la nueva contraseña.</p><Link to="/login" className="mt-7 inline-flex w-full justify-center rounded-xl bg-[#1454d8] px-5 py-3.5 text-sm font-black text-white">Iniciar sesión</Link></> : <><p className="eyebrow mt-7">Nuevo acceso</p><h1 className="mt-3 text-3xl font-black tracking-tight">Crea una contraseña nueva</h1><p className="mt-3 text-sm leading-6 text-[#6c798a]">Usa al menos 8 caracteres y evita contraseñas demasiado comunes.</p><form onSubmit={submit} className="mt-7 grid gap-4"><label className="text-sm font-bold">Nueva contraseña<input name="password" type="password" minLength={8} required autoComplete="new-password" className="mt-2 w-full rounded-xl border border-[#dce4ef] bg-[#f8fafc] px-4 py-3.5 outline-none focus:border-[#1454d8]" /></label><label className="text-sm font-bold">Confirmar contraseña<input name="password_confirm" type="password" minLength={8} required autoComplete="new-password" className="mt-2 w-full rounded-xl border border-[#dce4ef] bg-[#f8fafc] px-4 py-3.5 outline-none focus:border-[#1454d8]" /></label>{error && <p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<button disabled={loading} className="mt-1 rounded-xl bg-[#1454d8] px-5 py-3.5 text-sm font-black text-white disabled:opacity-60">{loading ? "Actualizando..." : "Guardar contraseña"}</button></form></>}</section></main>;
}
