import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Check, ExternalLink, FileSearch, X } from "lucide-react";
import { useState } from "react";
import { reviewPaymentReceipt } from "../../api/orders";
import type { Order } from "../../types/order";

export function AdminReceiptReview({ order }: { order: Order }) {
  const client = useQueryClient(); const [note, setNote] = useState(""); const receipt = order.payment_receipt;
  const review = useMutation({ mutationFn: (status: "approved" | "rejected") => reviewPaymentReceipt(order.order_number, status, note), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin", "order", order.order_number] }); client.invalidateQueries({ queryKey: ["admin", "orders"] }); }, onError: () => window.alert("No fue posible revisar el comprobante.") });
  if (!receipt) return <section className="rounded-2xl border border-[#dfe7ef] bg-white p-5"><div className="flex items-center gap-2"><FileSearch size={18} className="text-[#8593a4]" /><h2 className="font-black">Comprobante</h2></div><p className="mt-4 text-xs leading-5 text-[#7a899b]">El cliente aún no ha adjuntado un comprobante.</p></section>;
  return <section className="rounded-2xl border border-[#dfe7ef] bg-white p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><FileSearch size={18} className="text-[#249fd3]" /><h2 className="font-black">Comprobante</h2></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${receipt.status === "approved" ? "bg-emerald-50 text-emerald-700" : receipt.status === "rejected" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{receipt.status_display}</span></div><a href={receipt.file_url} target="_blank" rel="noreferrer" className="mt-4 flex items-center justify-center gap-2 rounded-xl bg-[#eaf7fc] px-4 py-3 text-xs font-black text-[#249fd3]"><ExternalLink size={15} /> Abrir comprobante</a>{receipt.customer_note && <p className="mt-3 rounded-xl bg-[#f7f9fc] p-3 text-xs text-[#64758a]"><strong>Nota del cliente:</strong> {receipt.customer_note}</p>}{receipt.status === "pending" ? <><textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={255} placeholder="Observación para el cliente (opcional)" className="mt-4 min-h-20 w-full rounded-xl border border-[#dce4ef] p-3 text-xs outline-none focus:border-[#249fd3]" /><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={review.isPending} onClick={() => review.mutate("rejected")} className="flex items-center justify-center gap-1 rounded-xl bg-red-50 px-3 py-3 text-xs font-black text-red-700"><X size={15} /> Rechazar</button><button disabled={review.isPending} onClick={() => review.mutate("approved")} className="flex items-center justify-center gap-1 rounded-xl bg-emerald-600 px-3 py-3 text-xs font-black text-white"><Check size={15} /> Aprobar pago</button></div></> : receipt.review_note && <p className="mt-3 text-xs leading-5 text-[#65758a]"><strong>Respuesta:</strong> {receipt.review_note}</p>}</section>;
}
