import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, CheckCircle2, MapPin, Package, Phone, ReceiptText, UserRound } from "lucide-react";
import { Link, useParams } from "react-router";

import { getAdminOrder, updateAdminOrderStatus, updateAdminPaymentStatus } from "../../api/orders";
import { AdminReceiptReview } from "../../components/admin/AdminReceiptReview";
import { AdminLoading, fieldClass } from "../../components/admin/AdminUi";
import { orderStatusClasses, paymentStatusClasses } from "../../lib/order-status";
import type { OrderStatus, PaymentStatus } from "../../types/order";

const money = new Intl.NumberFormat("es-PE", { style: "currency", currency: "PEN" });

export function AdminOrderDetailPage() {
  const { orderNumber = "" } = useParams();
  const client = useQueryClient();
  const order = useQuery({ queryKey: ["admin", "order", orderNumber], queryFn: () => getAdminOrder(orderNumber) });
  const statusMutation = useMutation({ mutationFn: (status: OrderStatus) => updateAdminOrderStatus(orderNumber, status), onSuccess: (data) => { client.setQueryData(["admin", "order", orderNumber], data); client.invalidateQueries({ queryKey: ["admin", "orders"] }); }, onError: () => window.alert("No se pudo cambiar el estado. Verifica la transición seleccionada.") });
  const paymentMutation = useMutation({ mutationFn: (status: PaymentStatus) => updateAdminPaymentStatus(orderNumber, status), onSuccess: (data) => { client.setQueryData(["admin", "order", orderNumber], data); client.invalidateQueries({ queryKey: ["admin", "orders"] }); }, onError: () => window.alert("No se pudo actualizar el pago.") });
  if (order.isPending) return <AdminLoading />;
  if (!order.data) return <div className="rounded-2xl bg-white p-10 text-center"><p className="font-black">Pedido no encontrado</p><Link to="/admin/orders" className="mt-3 inline-block text-sm font-bold text-[#1454d8]">Volver a pedidos</Link></div>;
  const data = order.data;
  return <>
    <Link to="/admin/orders" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-[#607086] hover:text-[#1454d8]"><ArrowLeft size={17} /> Volver a pedidos</Link>
    <div className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[0.2em] text-[#1454d8]">Detalle de venta</p><h1 className="mt-2 text-3xl font-black tracking-tight">{data.order_number}</h1><p className="mt-2 text-sm text-[#758397]">Creado el {new Date(data.created_at).toLocaleString("es-PE")}</p></div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-2 text-xs font-black ${orderStatusClasses[data.status]}`}>{data.status_display}</span><span className={`rounded-full px-3 py-2 text-xs font-black ${paymentStatusClasses[data.payment_status]}`}>{data.payment_status_display}</span></div></div>
    <div className="mb-6 ml-auto max-w-md"><AdminReceiptReview order={data} /></div>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_0.8fr]">
      <div className="grid gap-6"><section className="overflow-hidden rounded-2xl border border-[#dfe7ef] bg-white"><div className="flex items-center gap-2 border-b border-[#e8edf3] px-5 py-4"><Package size={18} className="text-[#1454d8]" /><h2 className="font-black">Productos del pedido</h2></div><div className="divide-y divide-[#edf1f5]">{data.items.map((item) => <div key={item.id} className="flex items-center gap-4 px-5 py-4"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-[#f1f5f9] text-xs font-black text-[#52657d]">×{item.quantity}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-black">{item.product_name}</p><p className="mt-1 text-xs text-[#7d8a99]">{item.product_sku} · {money.format(Number(item.unit_price))} c/u</p></div><strong className="text-sm">{money.format(Number(item.subtotal))}</strong></div>)}</div><div className="ml-auto w-full max-w-sm border-t border-[#e8edf3] p-5"><div className="flex justify-between text-sm text-[#718095]"><span>Subtotal</span><span>{money.format(Number(data.subtotal))}</span></div><div className="mt-2 flex justify-between text-sm text-[#718095]"><span>Envío</span><span>{money.format(Number(data.shipping_cost))}</span></div><div className="mt-4 flex justify-between border-t border-[#e8edf3] pt-4 text-lg font-black"><span>Total</span><span>{money.format(Number(data.total))}</span></div></div></section>
        <section className="rounded-2xl border border-[#dfe7ef] bg-white p-5"><div className="flex items-center gap-2"><UserRound size={18} className="text-[#1454d8]" /><h2 className="font-black">Entrega y contacto</h2></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><p className="text-xs font-bold text-[#8190a2]">Destinatario</p><p className="mt-1 text-sm font-black">{data.recipient_name}</p><p className="mt-2 flex items-center gap-2 text-sm text-[#596a80]"><Phone size={15} /> {data.recipient_phone}</p></div><div><p className="text-xs font-bold text-[#8190a2]">Dirección</p><p className="mt-1 flex gap-2 text-sm font-semibold leading-6"><MapPin size={16} className="mt-1 shrink-0 text-[#1454d8]" /> {data.address}, {data.district}, {data.province}, {data.department}</p>{data.address_reference && <p className="mt-1 text-xs text-[#7c8999]">Ref.: {data.address_reference}</p>}</div></div>{data.notes && <div className="mt-5 rounded-xl bg-[#f5f8fc] p-4 text-sm text-[#586a80]"><strong>Observaciones:</strong> {data.notes}</div>}</section>
      </div>
      <aside className="grid h-fit gap-5"><section className="rounded-2xl border border-[#dfe7ef] bg-white p-5"><div className="flex items-center gap-2"><CheckCircle2 size={18} className="text-[#1454d8]" /><h2 className="font-black">Gestionar pedido</h2></div><label className="mt-5 block text-sm font-bold">Estado del pedido<select value={data.status} disabled={statusMutation.isPending || ["delivered", "cancelled"].includes(data.status)} onChange={(event) => statusMutation.mutate(event.target.value as OrderStatus)} className={fieldClass}><option value="pending" disabled>Pendiente</option><option value="confirmed">Confirmado</option><option value="processing">En preparación</option><option value="shipped">Enviado</option><option value="delivered">Entregado</option><option value="cancelled">Cancelado</option></select></label><label className="mt-4 block text-sm font-bold">Estado del pago<select value={data.payment_status} disabled={paymentMutation.isPending} onChange={(event) => paymentMutation.mutate(event.target.value as PaymentStatus)} className={fieldClass}><option value="pending">Pendiente</option><option value="paid">Pagado</option><option value="failed">Fallido</option><option value="refunded">Reembolsado</option></select></label><p className="mt-4 text-xs leading-5 text-[#7b8999]">Al cancelar un pedido, el sistema devuelve automáticamente sus unidades al inventario.</p></section><section className="rounded-2xl border border-[#dfe7ef] bg-white p-5"><div className="flex items-center gap-2"><ReceiptText size={18} className="text-[#1454d8]" /><h2 className="font-black">Información de pago</h2></div><dl className="mt-5 grid gap-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-[#758397]">Método</dt><dd className="text-right font-black">{data.payment_method_display}</dd></div><div className="flex justify-between gap-3"><dt className="text-[#758397]">Última actualización</dt><dd className="text-right font-black">{new Date(data.updated_at).toLocaleString("es-PE")}</dd></div></dl></section></aside>
    </div>
  </>;
}
