# Generated by Django 6.0.7 on 2026-07-20 16:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=230, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='descripción corta')),
                ('description', models.TextField(verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio de oferta')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('refurbished', 'Reacondicionado'), ('used', 'Usado')], default='new', max_length=20, verbose_name='condición')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='especificaciones técnicas')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='brands.brand', verbose_name='marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='texto alternativo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='imagen principal')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de productos',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'category'], name='products_pr_brand_i_98ddd0_idx'),
        ),
    ]
